const ACTIVE_KEY = "loveDefense.activeConversation"
const COMPLETED_KEY = "loveDefense.completedConversations"
const LEAGUE_KEY = "loveDefense.leagueProgress"
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) ?? "null") ?? fallback } catch { return fallback } }
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value))
export const loadActiveConversation = () => read(ACTIVE_KEY, null)
export const saveActiveConversation = (session) => { if (session) write(ACTIVE_KEY, { ...session, updatedAt: new Date().toISOString() }); return session }
export const clearActiveConversation = () => localStorage.removeItem(ACTIVE_KEY)
export const loadCompletedConversations = () => read(COMPLETED_KEY, []).slice(0, 7)
export const completeConversation = (session) => { const completed = [{ ...session, status: session.status === "failed" ? "failed" : "completed", completedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, ...loadCompletedConversations()].slice(0, 7); write(COMPLETED_KEY, completed); clearActiveConversation(); return completed }
export const loadLeagueProgress = () => read(LEAGUE_KEY, { currentTier: "배치 중", highestTier: "배치 중", totalCompletedGames: 0, totalClearedGames: 0, currentClearStreak: 0, bestClearStreak: 0, currentPerfectClearStreak: 0, bestPerfectClearStreak: 0, totalPerfectClears: 0, updatedAt: new Date().toISOString() })
export const saveLeagueProgress = (value) => { write(LEAGUE_KEY, { ...value, updatedAt: new Date().toISOString() }); return value }
export function calculateTier(progress) { if (progress.totalPerfectClears >= 10) return "그랜드 마스터"; if (progress.currentPerfectClearStreak >= 5) return "마스터"; if (progress.currentPerfectClearStreak >= 3) return "다이아"; if (progress.currentClearStreak >= 7) return "플래티넘"; if (progress.currentClearStreak >= 5) return "골드"; if (progress.currentClearStreak >= 3) return "실버"; if (progress.totalClearedGames >= 1) return "브론즈"; return "배치 중" }
export function updateLeagueProgress(previous, session) { const cleared = session.status === "completed"; const perfect = cleared && session.relationshipHp === 100; const next = { ...previous, totalCompletedGames: previous.totalCompletedGames + 1, totalClearedGames: previous.totalClearedGames + (cleared ? 1 : 0), currentClearStreak: cleared ? previous.currentClearStreak + 1 : 0, currentPerfectClearStreak: perfect ? previous.currentPerfectClearStreak + 1 : 0, totalPerfectClears: previous.totalPerfectClears + (perfect ? 1 : 0) }; next.bestClearStreak = Math.max(next.bestClearStreak, next.currentClearStreak); next.bestPerfectClearStreak = Math.max(next.bestPerfectClearStreak, next.currentPerfectClearStreak); next.currentTier = calculateTier(next); const tierRank = ["배치 중", "브론즈", "실버", "골드", "플래티넘", "다이아", "마스터", "그랜드 마스터", "챌린저"]; next.highestTier = tierRank.indexOf(next.currentTier) > tierRank.indexOf(previous.highestTier) ? next.currentTier : previous.highestTier; return saveLeagueProgress(next) }
