export const COACHING_KNOWLEDGE_VERSION = "2026-07-15.1"

const source = (id) => ({
  id: `love-defense-coaching-${id}`,
  label: "연애 디펜스 큐레이션 코칭 Seed",
  type: "project_curated_seed",
})

export const coachingKnowledgeCards = [
  {
    id: "emotion_validation_before_solution",
    title: "해결책보다 감정 확인을 먼저 하기",
    topics: ["감정 확인", "서운함", "공감", "해결책"],
    keywords: ["서운", "속상", "감정", "마음", "공감", "해결", "조언", "이해"],
    guidance: "상대의 감정을 추측으로 단정하지 말고 관찰한 사실과 들린 감정을 짧게 확인한 뒤, 더 듣고 싶은 지점을 한 가지 묻는다.",
    avoid: "감정을 확인하기 전에 해결책을 밀어붙이거나 '별일 아니다'라고 축소하지 않는다.",
    source: source("emotion-validation"),
  },
  {
    id: "need_clarification",
    title: "숨은 욕구를 확인하는 질문",
    topics: ["욕구 확인", "관심", "존중", "확신"],
    keywords: ["원해", "바라", "필요", "관심", "존중", "확신", "알아줘", "어떻게"],
    guidance: "상대가 원하는 것이 공감, 설명, 행동 변화 중 무엇인지 선택지를 강요하지 않는 질문으로 확인한다.",
    avoid: "상대의 욕구를 성격 결함이나 과도한 요구로 규정하지 않는다.",
    source: source("need-clarification"),
  },
  {
    id: "observation_without_blame",
    title: "비난 대신 관찰과 영향 말하기",
    topics: ["비난 완화", "관찰", "영향", "갈등"],
    keywords: ["항상", "맨날", "절대", "때문", "잘못", "책임", "비난", "무시"],
    guidance: "평가나 낙인 대신 확인 가능한 행동 한 가지와 그 행동이 자신에게 준 영향을 분리해 말한다.",
    avoid: "'넌 항상', '원래 그런 사람'처럼 사람 전체를 단정하지 않는다.",
    source: source("observation-without-blame"),
  },
  {
    id: "concrete_request",
    title: "작고 구체적인 행동 요청",
    topics: ["행동 요청", "합의", "재발 방지", "약속"],
    keywords: ["앞으로", "다음", "약속", "행동", "바꿔", "연락", "시간", "구체"],
    guidance: "상대가 실행 여부를 판단할 수 있도록 행동, 시점, 예외를 한 번에 하나씩 구체적으로 제안하고 조정 가능성을 남긴다.",
    avoid: "사랑을 증명하라는 식의 포괄적 요구나 지킬 수 없는 영구적인 약속을 요구하지 않는다.",
    source: source("concrete-request"),
  },
  {
    id: "repair_apology",
    title: "영향을 인정하는 사과와 관계 회복",
    topics: ["사과", "책임", "회복", "신뢰"],
    keywords: ["미안", "사과", "책임", "상처", "신뢰", "회복", "다시", "실수"],
    guidance: "의도 해명보다 상대가 받은 영향을 먼저 인정하고, 변명 없는 사과 뒤에 재발 방지 행동을 덧붙인다.",
    avoid: "'그럴 의도는 아니었어'만 반복하거나 상대의 반응 때문에 사과한다고 말하지 않는다.",
    source: source("repair-apology"),
  },
  {
    id: "autonomy_and_space",
    title: "회피가 아닌 안전한 대화 중단",
    topics: ["거리 두기", "자율성", "대화 중단", "회피"],
    keywords: ["혼자", "시간", "거리", "부담", "그만", "나중", "회피", "답장", "생각"],
    guidance: "잠시 멈출 필요를 존중하되 대화를 다시 시작할 구체적인 시점이나 신호를 함께 합의한다.",
    avoid: "즉답을 압박하거나 기약 없이 연락을 끊는 것을 합의로 오해하지 않는다.",
    source: source("autonomy-and-space"),
  },
  {
    id: "relationship_boundary",
    title: "관계의 경계를 행동 기준으로 합의하기",
    topics: ["경계", "존중", "친구", "제3자"],
    keywords: ["경계", "친구", "이성", "제3자", "질투", "연락", "숨겨", "존중"],
    guidance: "질투의 옳고 그름을 다투기보다 두 사람이 불편해하는 구체적 행동과 허용 가능한 기준을 각각 말한다.",
    avoid: "불안을 조롱하거나 휴대전화 공개처럼 과도한 통제를 사랑의 증명으로 요구하지 않는다.",
    source: source("relationship-boundary"),
  },
  {
    id: "money_fairness",
    title: "금전 갈등은 숫자와 일정으로 합의하기",
    topics: ["금전", "비용", "공정성", "채무"],
    keywords: ["돈", "비용", "계산", "빌린", "갚", "금액", "지출", "공정", "영수증"],
    guidance: "감정과 금액을 분리해 확인하고 누가, 얼마를, 언제 부담하거나 갚을지 현실적인 일정으로 합의한다.",
    avoid: "사랑의 크기를 지출액으로 판단하거나 과거의 모든 비용을 한꺼번에 공격적으로 계산하지 않는다.",
    source: source("money-fairness"),
  },
  {
    id: "delayed_reply_reassurance",
    title: "답장 지연에서 사실과 불안을 분리하기",
    topics: ["답장 지연", "연락", "불안", "확인"],
    keywords: ["답장", "연락", "늦", "읽씹", "바빠", "불안", "확인", "기다"],
    guidance: "답장이 늦었다는 사실과 버림받았다는 해석을 분리하고, 바쁜 시간대의 최소 연락 기준을 함께 정한다.",
    avoid: "연속 메시지나 관계를 시험하는 말로 즉각적인 확답을 강요하지 않는다.",
    source: source("delayed-reply"),
  },
  {
    id: "safety_before_conflict",
    title: "안전 문제를 감정 논쟁보다 먼저 처리하기",
    topics: ["안전", "귀가", "밤", "보호"],
    keywords: ["안전", "귀가", "밤", "막차", "배터리", "위험", "데려다", "도착"],
    guidance: "늦은 밤이나 이동 상황에서는 먼저 안전한 귀가 방법과 확인 시점을 정한 뒤 감정 대화를 이어간다.",
    avoid: "안전을 사랑의 시험으로 만들거나 위험한 상황에서 긴 논쟁을 계속하지 않는다.",
    source: source("safety-first"),
  },
  {
    id: "deescalation_pause",
    title: "감정 강도가 높을 때 대화를 낮추기",
    topics: ["갈등 완화", "분노", "중단", "재개"],
    keywords: ["화", "소리", "욕", "싸움", "흥분", "진정", "공격", "갈등", "그만"],
    guidance: "감정 강도가 높으면 핵심 쟁점을 하나로 줄이고 짧게 확인한 뒤, 필요하면 재개 시간을 정해 잠시 멈춘다.",
    avoid: "이기기 위한 반박을 이어가거나 모욕과 위협을 대화 기술로 정상화하지 않는다.",
    source: source("deescalation"),
  },
  {
    id: "balanced_listening",
    title: "요약 확인 후 자신의 입장 말하기",
    topics: ["경청", "요약", "상호성", "대화"],
    keywords: ["듣", "말", "대화", "입장", "설명", "오해", "이해", "서로"],
    guidance: "상대의 핵심 감정이나 요청을 한 문장으로 요약해 맞는지 확인한 뒤 자신의 입장을 짧게 덧붙인다.",
    avoid: "질문만 연속해서 심문처럼 만들거나 자신의 필요를 계속 숨기지 않는다.",
    source: source("balanced-listening"),
  },
]
