create extension if not exists pgcrypto;

-- Existing user data is preserved. These nullable columns let the profile UI
-- store the new gender/tendency fields without resetting old profiles.
alter table if exists profiles add column if not exists gender text check (gender in ('male','female') or gender is null);
alter table if exists profiles add column if not exists tendency text;
alter table if exists profiles add column if not exists dialogue_diversity jsonb not null default '{}';

create table if not exists profiles (user_id uuid primary key references auth.users(id) on delete cascade, nickname text not null check (char_length(trim(nickname)) between 2 and 20), mbti text check (mbti is null or upper(mbti) in ('INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP')), gender text check (gender in ('male','female') or gender is null), tendency text, expression_style text check (expression_style in ('direct','indirect') or expression_style is null), desired_response text check (desired_response in ('empathy','solution') or desired_response is null), conflict_style text check (conflict_style in ('approach','distance') or conflict_style is null), relationship_need text check (relationship_need in ('assurance','autonomy') or relationship_need is null), relationship_duration text, frequent_conflict_topics text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists partner_profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text, expression_style text check (expression_style in ('direct','indirect') or expression_style is null), desired_response text check (desired_response in ('empathy','solution') or desired_response is null), conflict_style text check (conflict_style in ('approach','distance') or conflict_style is null), relationship_need text check (relationship_need in ('assurance','autonomy') or relationship_need is null), notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists game_sessions (id uuid primary key default gen_random_uuid(), client_session_id uuid not null, user_id uuid not null references auth.users(id) on delete cascade, mode text not null check (mode in ('daily_date','practice','league')), difficulty text not null check (difficulty in ('easy','normal','hard')), blame_side text not null check (blame_side in ('partner','me')), selected_categories text[] not null default '{}', started_at timestamptz not null, ended_at timestamptz, end_reason text check (end_reason in ('completed','user_exit','hp_zero','interrupted') or end_reason is null), cleared_stages integer not null default 0 check (cleared_stages >= 0), total_stages_played integer not null default 0 check (total_stages_played >= 0), first_try_correct integer not null default 0 check (first_try_correct >= 0), wrong_answer_count integer not null default 0 check (wrong_answer_count >= 0), total_score integer not null default 0 check (total_score between 0 and 100000), context_score integer not null default 0 check (context_score between 0 and 100), emotion_score integer not null default 0 check (emotion_score between 0 and 100), communication_score integer not null default 0 check (communication_score between 0 and 100), non_leap_score integer not null default 0 check (non_leap_score between 0 and 100), is_completed boolean not null default false, is_ranked boolean not null default false, schema_version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, client_session_id));
create table if not exists stage_results (id uuid primary key default gen_random_uuid(), session_id uuid not null references game_sessions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, stage_number integer not null check (stage_number >= 1), scenario_id text not null, scenario_title text not null, mode text not null, difficulty text not null, category_tags text[] not null default '{}', selected_option_id text, best_option_id text, attempt_count integer not null default 0 check (attempt_count >= 0), wrong_answer_count integer not null default 0 check (wrong_answer_count >= 0), cleared boolean not null default false, hp_remaining integer not null default 100 check (hp_remaining between 0 and 100), context_score numeric not null default 0 check (context_score between 0 and 100), emotion_score numeric not null default 0 check (emotion_score between 0 and 100), communication_score numeric not null default 0 check (communication_score between 0 and 100), non_leap_score numeric not null default 0 check (non_leap_score between 0 and 100), feedback jsonb not null default '{}', recommended_expression text, stage_payload jsonb, created_at timestamptz not null default now(), unique(session_id, stage_number));
create table if not exists saved_expressions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, expression_text text not null, scenario_title text, category_tags text[] not null default '{}', source_session_id uuid references game_sessions(id) on delete set null, source_stage_id uuid references stage_results(id) on delete set null, memo text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, expression_text));
create table if not exists scenario_history (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, scenario_id text not null, mode text not null, difficulty text not null, blame_side text not null, category_tags text[] not null default '{}', title text not null, context_summary text not null, opening_line text, fingerprint text not null, created_at timestamptz not null default now(), unique(user_id, fingerprint));
create table if not exists leaderboard_entries (user_id uuid primary key references auth.users(id) on delete cascade, nickname text not null, best_score integer not null default 0, highest_stage integer not null default 0, first_try_correct integer not null default 0, wrong_answer_count integer not null default 0, achieved_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists user_badges (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, badge_code text not null, badge_name text not null, badge_description text, earned_at timestamptz not null default now(), metadata jsonb not null default '{}', unique(user_id, badge_code));
create or replace function set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','partner_profiles','game_sessions','saved_expressions','leaderboard_entries'] loop execute format('drop trigger if exists %I_updated_at on %I', t, t); execute format('create trigger %I_updated_at before update on %I for each row execute function set_updated_at()', t, t); end loop; end $$;
