import { useEffect, useMemo, useRef, useState } from "react"
import { categories, scenarios } from "./data/scenarios"
import { bootstrapApp } from "./appBootstrap"
import { friendlyError } from "./services/supabaseClient"
import { defaultUser, loadHistory, loadSavedExpressions, loadUser } from "./lib/storage"
import { getProfile, upsertProfile } from "./repositories/profileRepository"
import { getSavedExpressions, saveExpression as saveServerExpression } from "./repositories/expressionRepository"
import { getRecentSessions, createGameSession, saveStageResult, finalizeGameSession } from "./repositories/gameRepository"
import { getLeaderboard, getMyRank, submitRankedResult } from "./repositories/rankingRepository"
import { enqueueSync, syncPendingQueue } from "./services/syncService"

const tabs = [["home", "홈", "⌂"], ["practice", "연습", "✦"], ["league", "리그", "♛"], ["profile", "사용자", "◉"]]
export default function App() {
  const [ready, setReady] = useState(false); const [configError, setConfigError] = useState(""); const [page, setPage] = useState("landing")
  const [user, setUser] = useState(loadUser); const [history, setHistory] = useState(loadHistory); const [savedExpressions, setSavedExpressions] = useState(loadSavedExpressions)
  const [selected, setSelected] = useState([]); const [scenarioIndex, setScenarioIndex] = useState(0); const [stage, setStage] = useState(0); const [score, setScore] = useState(0); const [wrong, setWrong] = useState(0); const [feedback, setFeedback] = useState(""); const [lastResult, setLastResult] = useState(null); const [sessionId, setSessionId] = useState(null); const [status, setStatus] = useState(""); const [leaderboard, setLeaderboard] = useState([]); const [myRank, setMyRank] = useState("--")
  useEffect(() => { (async () => { const boot = await bootstrapApp("love-defense"); if (boot.error) setConfigError(boot.error.message ?? friendlyError(boot.error)); else { const p = await getProfile(); if (p.data) setUser((x) => ({ ...x, nickname: p.data.nickname, mbti: p.data.mbti ?? x.mbti, expression: p.data.expression_style === "indirect" ? "간접 표현형" : "직접 표현형", relationshipLength: p.data.relationship_duration ?? "" })); const [games, expressions] = await Promise.all([getRecentSessions(), getSavedExpressions()]); if (!games.error) setHistory(games.data.map((x) => ({ id: x.id, score: x.total_score, stage: x.cleared_stages, success: x.is_completed, scenario: "서버 기록", createdAt: x.created_at }))); if (!expressions.error) setSavedExpressions(expressions.data.map((x) => x.expression_text)) } setReady(true) })() }, [])
  useEffect(() => { if (ready && page === "league") Promise.all([getLeaderboard(50), getMyRank()]).then(([board, rank]) => { if (!board.error) setLeaderboard(board.data); if (!rank.error) setMyRank(rank.data ?? "--") }) }, [page, ready])
  async function retrySync() { await syncPendingQueue(async (item) => { if (item.operationType === "SAVE_PROFILE") { const r = await upsertProfile(item.payload); if (r.error) throw r.error } else if (item.operationType === "SAVE_EXPRESSION") { const r = await saveServerExpression(item.payload); if (r.error) throw r.error } else if (item.operationType === "SAVE_GAME_RESULT") { const r = await createGameSession({ client_session_id: item.payload.operationId ?? crypto.randomUUID(), mode: "practice", difficulty: "normal", blame_side: "partner", started_at: item.payload.createdAt ?? new Date().toISOString(), ended_at: item.payload.createdAt ?? new Date().toISOString(), end_reason: item.payload.success ? "completed" : "hp_zero", cleared_stages: item.payload.stage ?? 0, total_score: item.payload.score ?? 0, is_completed: Boolean(item.payload.success) }); if (r.error) throw r.error } }) }
  useEffect(() => { if (!ready) return; const handler = () => retrySync(); window.addEventListener("online", handler); return () => window.removeEventListener("online", handler) }, [ready])
  const scenario = scenarios[scenarioIndex]; const matching = useMemo(() => scenarios.filter((x) => selected.some((tag) => x.tags.includes(tag))), [selected]); const bestScore = Math.max(0, ...history.map((x) => Number(x.score) || 0))
  const go = (next) => { setPage(next); window.scrollTo({ top: 0, behavior: "smooth" }) }
  async function startGame() { const next = matching[0] ?? scenarios[0]; setScenarioIndex(scenarios.indexOf(next)); setStage(0); setScore(0); setWrong(0); setFeedback(""); const client_session_id = crypto.randomUUID(); const created = await createGameSession({ client_session_id, mode: "practice", difficulty: "normal", blame_side: "partner", selected_categories: selected, started_at: new Date().toISOString(), total_stages_played: scenarios.length }); if (created.error) enqueueSync("SAVE_GAME_RESULT", { operationId: client_session_id }); else setSessionId(created.data.id); go("chat") }
  async function finishGame(finalScore, success) { const result = { score: finalScore, stage: stage + 1, success, scenario: scenario.title, createdAt: new Date().toISOString() }; setLastResult(result); setHistory((x) => [{ ...result, id: crypto.randomUUID() }, ...x]); if (sessionId) { const saved = await finalizeGameSession(sessionId, { ended_at: result.createdAt, end_reason: success ? "completed" : "hp_zero", cleared_stages: result.stage, total_score: finalScore, is_completed: success }); if (saved.error) enqueueSync("SAVE_GAME_RESULT", result); else await submitRankedResult({ session_id: sessionId, total_score: finalScore, cleared_stages: result.stage, first_try_correct: success ? result.stage : 0, wrong_answer_count: wrong }) } go("result") }
  const choosingRef = useRef(false)
  async function choose(option) {
    if (choosingRef.current) return { ignored: true }
    choosingRef.current = true
    if (!option.correct) { const next = wrong + 1; setWrong(next); setFeedback(option.feedback); if (next >= 2) finishGame(score, false); choosingRef.current = false; return { correct: false, terminal: next >= 2 } }
    const nextScore = score + 100; setFeedback("상대의 감정을 먼저 확인하고 마음에 가까운 반응을 골랐어요.")
    if (sessionId) await saveStageResult({ session_id: sessionId, stage_number: stage + 1, scenario_id: scenario.id, scenario_title: scenario.title, mode: "practice", difficulty: "normal", category_tags: scenario.tags, selected_option_id: option.text, best_option_id: option.text, attempt_count: wrong + 1, wrong_answer_count: wrong, cleared: true, hp_remaining: 100, context_score: 100, emotion_score: 100, communication_score: 100, non_leap_score: 100, feedback: {} })
    if (stage >= scenarios.length - 1) finishGame(nextScore, true); else { setScore(nextScore); setStage(stage + 1); setScenarioIndex((scenarioIndex + 1) % scenarios.length); setWrong(0) }
    choosingRef.current = false
    return { correct: true, terminal: stage >= scenarios.length - 1 }
  }
  async function updateProfile(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const next = { ...user, nickname: form.get("nickname") || defaultUser.nickname, mbti: form.get("mbti") || "INFP", relationshipLength: form.get("relationshipLength") || "" }; setUser(next); const saved = await upsertProfile({ nickname: next.nickname, mbti: next.mbti, expression_style: next.expression === "간접 표현형" ? "indirect" : "direct", relationship_duration: next.relationshipLength }); if (saved.error) { enqueueSync("SAVE_PROFILE", next, saved.error); setStatus("저장하지 못했습니다. 임시 보관 후 다시 시도합니다.") } else setStatus("서버에 저장되었습니다."); go("profile") }
  async function saveRecommended() { const text = scenario.options.find((x) => x.correct)?.text; const saved = await saveServerExpression({ expression_text: text, scenario_title: scenario.title, category_tags: scenario.tags, source_session_id: sessionId }); if (saved.error) { enqueueSync("SAVE_EXPRESSION", { expression_text: text }, saved.error); setStatus("오프라인 임시 보관") } else { setSavedExpressions((x) => [text, ...x.filter((y) => y !== text)]); setStatus("서버에 저장되었습니다.") } }
  if (!ready) return <main className="phone-shell"><section className="section-block"><h2>서버 연결 준비 중</h2><p className="section-note">잠시만 기다려주세요. 문제가 있으면 설정 안내를 확인합니다.</p></section></main>
  if (configError) return <main className="phone-shell"><section className="section-block"><h2>Supabase 설정이 필요합니다</h2><p className="section-note">{configError}</p><p className="section-note">프로젝트 루트에 .env를 만들고 VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY를 입력한 뒤 다시 실행해주세요.</p></section></main>
  if (page === "landing") return <Landing onStart={() => go("home")} onProfile={() => go("profile")} />
  if (page === "chat") return <Chat key={`${stage}-${scenario.id}`} scenario={scenario} stage={stage} score={score} wrong={wrong} feedback={feedback} onChoose={choose} onExit={() => go("home")} />
  if (page === "result") return <Result result={lastResult} saved={savedExpressions.includes(scenario.options.find((x) => x.correct)?.text)} onSave={saveRecommended} onHome={() => go("home")} onReplay={startGame} status={status} />
  return <Shell page={page} onNavigate={go}>{page === "home" && <Home user={user} history={history} onStart={startGame} />}{page === "practice" && <Practice selected={selected} onToggle={(x) => setSelected((s) => s.includes(x) ? s.filter((y) => y !== x) : [...s, x])} onStart={startGame} />}{page === "league" && <League history={history} bestScore={bestScore} leaderboard={leaderboard} myRank={myRank} />}{page === "profile" && <Profile user={user} savedExpressions={savedExpressions} onSubmit={updateProfile} status={status} />}</Shell>
}
function Landing({ onStart, onProfile }) { return <main className="phone-shell landing-shell"><section className="landing"><div className="landing-logo">♡</div><p className="eyebrow">RELATIONSHIP COMMUNICATION GAME</p><h1>사랑<br /><span>디펜스</span></h1><p className="landing-lead">상대의 마음을 읽고<br />우리의 대화를 지켜내는 게임</p><div className="landing-preview"><span>상대가 먼저 연락하지 않으면 서운해.</span><b>어떤 말이 마음에 닿을까요?</b></div><button className="button button-primary button-large button-wide" onClick={onStart}>게임 시작하기 <span>→</span></button><button className="text-button" onClick={onProfile}>내 성향 먼저 설정하기 <span>→</span></button></section></main> }
function Shell({ page, onNavigate, children }) { return <main className="phone-shell"><div className="app-scroll">{children}</div><nav className="bottom-tabs">{tabs.map(([id, label, icon]) => <button className={`bottom-tab ${page === id ? "is-active" : ""}`} key={id} onClick={() => onNavigate(id)}><span>{icon}</span><small>{label}</small></button>)}</nav></main> }
function PageHeader({ eyebrow, title, copy, mark }) { return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div><span className="header-mark">{mark}</span></header> }
function Home({ user, history, onStart }) { const latest = history[0]; return <><PageHeader eyebrow="LOVE DEFENSE" title={`안녕, ${user.nickname}`} copy="오늘도 대화의 마음을 천천히 살펴봐요." mark="✦" /><section className="hero-card"><div><p className="eyebrow">TODAY'S MISSION</p><h2>오늘의 일일 데이트</h2><p>상대의 감정을 먼저 읽고<br />마음에 닿는 말을 골라보세요.</p><button className="button button-light" onClick={onStart}>플레이하기 <span>→</span></button></div><div className="hero-orb">♡</div></section><section className="stats-row"><div className="mini-stat"><span>오늘의 방어력</span><strong>{latest?.score ?? 100}</strong><small>관계 HP</small></div><div className="mini-stat"><span>최근 점수</span><strong>{latest?.score ?? "--"}</strong><small>점수 / 100</small></div></section><article className="info-card accent-blue"><span className="card-icon">!</span><div><h3>오늘의 위험 포인트</h3><p>공감보다 해결책을 먼저 말하는 습관을 잠깐 멈춰보세요.</p></div></article><article className="summary-card"><div className="summary-top"><div><p className="eyebrow">RECENT RESULT</p><h3>최근 플레이 리포트</h3></div></div><div className="summary-metrics"><div><strong>{latest?.score ?? "--"}</strong><span>점수</span></div><div><strong>{latest?.stage ?? "--"}</strong><span>Stage</span></div><div><strong>{history.length || "--"}</strong><span>플레이</span></div></div></article></> }
function Practice({ selected, onToggle, onStart }) { return <><PageHeader eyebrow="TRAINING ROOM" title="연습" copy="지금 필요한 대화 상황을 골라보세요." mark="✦" /><section className="practice-hero"><div><span className="pill pill-dark">{categories.length}가지 주제</span><h2>다양한 상황 연습</h2><p>천천히, 감정부터 살펴보세요.</p></div><div className="practice-spark">✦</div></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">CHOOSE A TOPIC</p><h2>상황 카테고리</h2></div><span className="selection-count">{selected.length} / {categories.length}</span></div><div className="tag-list">{categories.map((x) => <button className={`tag ${selected.includes(x) ? "is-selected" : ""}`} key={x} onClick={() => onToggle(x)}>{x}</button>)}</div><button className="button button-primary button-wide" onClick={onStart}>선택한 상황 연습하기 <span>→</span></button></section></> }
function Chat({ scenario, stage, score, feedback, onChoose, onExit }) {
  const [sheet, setSheet] = useState("collapsed")
  const [locked, setLocked] = useState(false)
  const [disabled, setDisabled] = useState([])
  const [selectedCorrect, setSelectedCorrect] = useState(null)
  const [toast, setToast] = useState("")
  const [transition, setTransition] = useState(true)
  const [transitionLeaving, setTransitionLeaving] = useState(false)
  const [dragY, setDragY] = useState(0)
  const drag = useRef({ active: false, startY: 0 })
  const toastTimer = useRef(null)
  const transitionTimer = useRef(null)
  const playerRole = scenario.playerRole ?? { name: "나", gender: "unspecified", relationshipRole: "사용자" }
  const partnerRole = scenario.partnerRole ?? { name: "연인", gender: "unspecified", relationshipRole: "대화 상대" }
  const genderLabel = (gender) => ({ male: "남성", female: "여성", unspecified: "미설정" }[gender] ?? "미설정")
  const roleLine = (role) => `${role.relationshipRole ?? ""} ${role.name || "나"}`.trim()
  const perspective = scenario.playerPerspective ?? `${roleLine(playerRole)}의 입장`
  const objective = scenario.playerObjective ?? "상대방의 감정을 이해하고 대화를 이어가세요."
  useEffect(() => {
    transitionTimer.current = setTimeout(() => setTransitionLeaving(true), 2700)
    const hideTimer = setTimeout(() => setTransition(false), 3000)
    return () => { clearTimeout(transitionTimer.current); clearTimeout(hideTimer) }
  }, [stage, scenario.id])
  useEffect(() => () => clearTimeout(toastTimer.current), [])
  useEffect(() => {
    const onKey = (event) => { if (event.key === "Escape" && sheet === "expanded") setSheet("collapsed") }
    window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey)
  }, [sheet])
  function showWrongToast() { setToast("오답!"); clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(""), 2000) }
  async function selectOption(option) {
    if (locked || disabled.includes(option.text)) return
    setLocked(true)
    if (option.correct) { setSelectedCorrect(option.text); await new Promise((resolve) => setTimeout(resolve, 900)) }
    const result = await onChoose(option)
    if (result?.ignored) { setLocked(false); return }
    if (!option.correct) { setDisabled((items) => [...items, option.text]); showWrongToast(); setLocked(false) }
  }
  function pointerDown(event) { drag.current = { active: true, startY: event.clientY }; event.currentTarget.setPointerCapture?.(event.pointerId); setDragY(0) }
  function pointerMove(event) { if (drag.current.active) setDragY(Math.max(-240, Math.min(240, event.clientY - drag.current.startY))) }
  function pointerUp() { if (!drag.current.active) return; const moved = dragY; drag.current.active = false; setDragY(0); if (Math.abs(moved) < 12) setSheet((value) => value === "expanded" ? "collapsed" : "expanded"); else setSheet(moved < 0 ? "expanded" : "collapsed") }
  const sheetStyle = dragY ? { transform: `translateY(${dragY}px)` } : undefined
  return <main className="chat-page"><div className="chat-app">
    {transition && <div className={`stage-transition-overlay ${transitionLeaving ? "is-leaving" : ""}`} aria-live="polite"><strong>STAGE {stage + 1}</strong></div>}
    {toast && <div className="answer-toast answer-toast--wrong" aria-live="assertive">오답!</div>}
    <header className="chat-header"><button className="chat-back" onClick={onExit}>‹</button><div className="chat-title"><span className="online-dot" /><div><strong>AI 데이트 코치</strong><small>STAGE {stage + 1} · {score} POINTS</small></div></div><button className="chat-exit" onClick={onExit}>종료</button></header>
    <section className="stage-status"><div className="stage-badge"><span>STAGE</span><strong>{stage + 1}</strong></div><div className="stage-track"><span style={{ width: `${((stage + 1) / scenarios.length) * 100}%` }} /></div></section>
    <section className="role-guide"><div><span className="context-kicker">현재 당신의 역할</span><strong>{perspective}</strong><small>목표 · {objective}</small></div><div className="role-people"><p><b>당신</b>{roleLine(playerRole)} · {genderLabel(playerRole.gender)}</p><p><b>상대방</b>{roleLine(partnerRole)} · {genderLabel(partnerRole.gender)}</p></div></section>
    <section className="chat-context"><span className="context-kicker">CURRENT SCENE</span><strong>{scenario.title}</strong><small>{scenario.summary}</small></section>
    <section className="message-list">{scenario.messages.map((m, i) => <div className={`message ${m.speaker}`} key={i}>{m.text}</div>)}</section>{feedback && <section className="feedback-panel">{feedback}</section>}
    <section className={`option-panel option-sheet option-sheet--${sheet}`} style={sheetStyle}><button className="sheet-handle" aria-label="선택지 펼치기 또는 접기" aria-expanded={sheet === "expanded"} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><span /></button><div className="choice-heading"><strong>선택지 보기</strong><button className="sheet-toggle" onClick={() => setSheet((value) => value === "expanded" ? "collapsed" : "expanded")} aria-label={sheet === "expanded" ? "선택지 접기" : "선택지 펼치기"}>{sheet === "expanded" ? "⌄" : "⌃"}</button></div><div className="option-list">{scenario.options.map((o) => <button className={`option-button ${selectedCorrect === o.text ? "is-correct" : ""} ${disabled.includes(o.text) ? "is-disabled" : ""}`} disabled={locked || disabled.includes(o.text)} key={o.text} onClick={() => selectOption(o)}>{o.text}<span>{selectedCorrect === o.text ? "✓ 적절한 선택" : "→"}</span></button>)}</div></section>
  </div></main>
}
function Result({ result, saved, onSave, onHome, onReplay, status }) { return <main className="phone-shell result-shell"><section className="result-hero"><p className="eyebrow">{result?.success ? "DEFENSE COMPLETE" : "A LITTLE PAUSE"}</p><div className="result-orbit"><span>{result?.score ?? 0}</span><small>POINTS</small></div><h1>{result?.success ? "대화 방어 성공!" : "다음에는 마음을 먼저"}</h1><p>{result?.success ? "상대의 감정을 확인하고 마음에 가까운 반응을 골랐어요." : "괜찮아요. 한 번 더 천천히 살펴볼 수 있어요."}</p></section><section className="result-summary"><div><span>클리어 Stage</span><strong>{result?.stage ?? 0}</strong></div><div><span>상황</span><strong>{result?.scenario ?? "-"}</strong></div></section><section className="recommend-card"><p className="eyebrow">RECOMMENDED PHRASE</p><blockquote>“그렇게 느꼈구나. 네 마음을 먼저 듣고 싶어.”</blockquote><button className="button button-secondary button-wide" onClick={onSave}>{saved ? "저장했어요 ✓" : "추천 표현 저장"}</button>{status && <p className="section-note">{status}</p>}</section><div className="result-actions"><button className="button button-primary button-wide" onClick={onHome}>홈으로</button><button className="button button-secondary button-wide" onClick={onReplay}>다시 플레이</button></div></main> }
function League({ history, bestScore, leaderboard, myRank }) { return <><PageHeader eyebrow="WEEKLY LEAGUE" title="리그" copy="이번 주 대화 방어력을 확인해보세요." mark="♛" /><section className="league-card"><div className="league-badge">◆</div><div><span className="pill pill-light">CURRENT TIER</span><h2>{bestScore >= 300 ? "골드 리그" : "실버 리그"}</h2><p><strong>{bestScore}</strong> DEFENSE POINTS</p></div></section><section className="rank-summary"><div><span>최고 점수</span><strong>{bestScore}</strong></div><div><span>내 순위</span><strong>{myRank}</strong></div><div><span>총 플레이</span><strong>{history.length}</strong></div></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">GLOBAL LEADERBOARD</p><h2>서버 랭킹</h2></div></div>{leaderboard.length ? leaderboard.slice(0, 10).map((x, i) => <div className="history-row" key={x.user_id}><span>{i + 1}. {x.nickname}</span><strong>{x.best_score}점</strong></div>) : <p className="section-note">랭킹을 불러오는 중이거나 아직 기록이 없어요.</p>}</section></> }
function Profile({ user, savedExpressions, onSubmit, status }) { return <><PageHeader eyebrow="MY SPACE" title="사용자" copy="나에게 맞는 대화 연습을 설계해요." mark="◉" /><section className="profile-card"><div className="avatar">☆</div><div><h2>{user.nickname}</h2><p>{user.mbti} · {user.expression}</p></div></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">PERSONAL SETTINGS</p><h2>내 성향</h2></div></div><form className="profile-form" onSubmit={onSubmit}><label>닉네임<input name="nickname" defaultValue={user.nickname} maxLength="20" required /></label><label>MBTI<input name="mbti" defaultValue={user.mbti} maxLength="4" /></label><label>연애 기간<input name="relationshipLength" defaultValue={user.relationshipLength} placeholder="예: 6개월" /></label><button className="button button-primary button-wide" type="submit">내 성향 저장하기</button>{status && <p className="section-note">{status}</p>}</form></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">SAVED PHRASES</p><h2>저장한 추천 표현</h2></div></div>{savedExpressions.length ? savedExpressions.map((x) => <blockquote className="saved-phrase" key={x}>{x}</blockquote>) : <p className="section-note">플레이 후 마음에 드는 표현을 저장해보세요.</p>}</section></> }
